### PR TITLE
Fix #268: create empty nodes for missing translations

### LINKED ISSUE #268: Bug: create short label for all translations
https://forum.getodk.org/t/collect-crashes-when-switching-languages/36056/9

Repro:
Create form
Add short labels
Add language
Don't fill in short labels in new language
Deploy form to Central (no error)
Fill form in Android, switch lang, collect crashes.

### PR DESCRIPTION
**Pull request by florianm**
This patch fixes a bug that was introduced through added support for extras (short label, guidance hint, image labels etc).
This patch has been split out from #266 as requested.

* Closes #268 
* Refactor data.js: pushChildren
* Improve function docs for pushChildren and addTranslation

### CODE REVIEW

**Comment by issa-tseng** [comment]
i have not tested or verified this, but the changes look simple enough.

File: public/javascripts/data.js [hunk 1]
```diff
@@ -219,41 +219,72 @@ var dataNS = odkmaker.namespace.load('odkmaker.data');
...
-    var pushChildren = function(arr, ext, frm, txn, pre)
-    {
-        var pre = (typeof pre !== 'undefined') ? pre : "";
-        // Only create a node for non-empty control object values
-        if ((ext !== undefined) && !_.isEmpty(ext[txn._languageCode]))
-        {
+    var pushChildren = function (arr, ext, frm, txn, pre) {
+        var pre = (pre !== undefined) ? pre : "";
+
+        // #268: skip unless ext contains at least one non-empty value
```
Comment (florianm) [inline public/javascripts/data.js:242]: We test whether e.g. English (first lang) has a value given, while other added languages are empty. In that case, we'll want empty nodes. Only if nothing is given, we can skip creating nodes.

File: public/javascripts/data.js [hunk 2]
```diff
@@ -219,41 +219,72 @@ var dataNS = odkmaker.namespace.load('odkmaker.data');
...
-                        children: getTranslation(ext, txn, prefix = pre)
-                    });
+                name: 'value',
+                attrs: {
+                    form: frm
+                },
+                _noWhitespace: true,
+                children: getTranslation(ext, txn, prefix = pre)
+            });
+        } else if ((ext !== undefined) && contains_non_empty_value && _.isEmpty(ext[txn._languageCode])) {
```
Comment (florianm) [inline public/javascripts/data.js:260]: If any other language contains a non empty value (`contains_non_empty_value`) but this translation is empty (`isEmpty...`), then push an empty node.

File: public/javascripts/data.js [hunk 3]
```diff
@@ -262,7 +293,7 @@ var dataNS = odkmaker.namespace.load('odkmaker.data');
         {
 
             // The translation for the main control object obj
-            var schoolyard = [{
+            var tx = [{
```
Comment (florianm) [inline public/javascripts/data.js:296]: Rename variable because the pushing children across a schoolyard has no explanatory value.

**Review by yanokwa — APPROVED** [review]
LGTM
